### ISSUE TITLE
Incorrect replacement

### ISSUE THREAD

**Issue by SSMK-wq** [fschaeck/python-pptx-text-replacer#6]
The same stack overflow issue still exists.

My raw data is like below

![image](https://user-images.githubusercontent.com/30723825/184502713-74abeaf3-dd95-49a6-afc9-cbfd8e8a2b61.png)

Your code output is like below

I guess your code is getting confused here because all the text is inside one box (but multiple lines)

![image](https://user-images.githubusercontent.com/30723825/184502769-72270634-932a-4fde-868b-a9fe5dcb93f8.png)

In the print message, the textframe and paragraph of that slide looks like below (with some weird characters or spaces)

TextFrame: 'Company AP Alignment 2021AUTOMOTIVEAP Business Plan FY2122xx NOV 2021, Time: xx:xx – xx:xx hrs (60mins)'
        Paragraph[0]: 'Company AP Alignment 2021AUTOMOTIVEAP Business Plan FY2122xx NOV 2021, Time: xx:xx – xx:xx hrs (60mins)'

Instead of diamond shapes shown here in github, in my jupyter notebook, it displays like below in square form

![image](https://user-images.githubusercontent.com/30723825/184503012-caff9422-e726-4b4a-9aab-bc6f2dc8a0c5.png)

And the run looks like below

![image](https://user-images.githubusercontent.com/30723825/184502897-cf876c35-afbb-4f82-bee8-72bfad4164d9.png)

Am sharing the full keyword list for you to understand (in case if it is overwriting - which I don't think so)

```
replacer.replace_text([('FY21/22','FY22/23'),('FY_2021','FY21/22'),('FY20/21','FY21/22'),('GA2021','GA2022'),
                       ('GA2020','GA2022'),('SEP-2022','SEP-2023'),('SEP-2021','SEP-2022'),('OCT-2021','OCT-2022'),
                       ('OCT-2020','OCT-2021'),('OCT 2021','OCT 2022'),('NOV 2021','NOV 2022'),('FY2122','FY22/23'),
                       ('FY2021','FY21/22'),('FY1920','FY20/21'),('FY_2122','FY22/23'),
                       ('FY21/22 / FY22/23','FY21/22 or FY22/23'),
                       ('F21Y22','FY22/23'),
                       ('your FY20 FCST','your FY22/23 FCST'),
                       ('your FY21/22 FCST','your FY22/23 FCST'),
                       ('Q2/FY22/23','Q2-FY22/23'),
                       ('JAN-22','JAN-23'),
                       ('FY19/20','FY20/21')]) 
```

**Comment by fschaeck** [comment]
I think I have a solution for this one. The unprintable characters in the text frame‘s and paragraph‘s texts are probably formatting characters for horizontal or vertical alignment coming from the run‘s font configuration. And since those are not part of a run‘s text, my replacement code gets out of sync…

I just avoid using those text fields and create my own by joining all the runs. I‘ll get that done tomorrow I think. And since I am at it, I’ll make sure, those diamonds are replaced by proper Unicode escape codes.

Concerning your replacement list: look at the script output at the very beginning! There are some warnings printed, that you should check closely!

**Comment by SSMK-wq** [comment]
@fschaeck - Sure, that would be really helpful. For warning messages in output, I opened a new issue. btw, in PPT, no diamond shapes are seen. When I paste your print message in github, it comes up with diamond shapes. but the  actual print message in jupyter notebook just has only question marks (within square box) as shown in my previous comment.

**Comment by fschaeck** [comment]
I just uploaded version 0.0.3 to PyPI and you can update the package in your notebook. This issue should be taken care of with the new version. Please close this issue if that holds true. ;-) I also change the question marks to be printed as unicode escape sequences. Therefore you will see things like \u0009 in the output instead of those squares or diamonds.

**Comment by SSMK-wq** [comment]
fantastic work. Latest update resolved the issue for text.
