### ISSUE TITLE
Understanding warning message

### ISSUE THREAD

**Issue by SSMK-wq** [fschaeck/python-pptx-text-replacer#7]
I executed your script and as part of output print message, I see the below warning. I thought of opening a new issue to discussing instead of hijacking the other thread..

```
WARNING: Match/Replacement ('FY21/22 / FY22/23','FY21/22 or FY22/23') at index 16 will never match due to match/replacement ('FY21/22','FY22/23') at index 0
WARNING: Match/Replacement ('your FY21/22 POS FCST','your FY22/23 POS FCST') at index 19 is obsolete due to match/replacement ('FY21/22','FY22/23') at index 0
```

Can help me understand what does this warning mean? 

Though it doesn't replace because there is an overlap in keywords list (but separately they are different keywords)

I understand the below
a)  index positions are based on tuple ordering.
b) I can just choose "to be replaced" keyword (FY21/22) instead of selecting multiple keywords like "your FY21/22 POS FCST". I did this sort of keyword selection because of old script (due to run issues). So, you think this can be avoided now?
c) But still, if I wish to replace "'FY21/22 / FY22/23"  to "FY21/22 or FY22/23", we will always have this warning (and it will not replace)? Because I only wish to introduce "or" instead of "/" (slash) but I can't just replace "/" with "or", then it will do at all the places (which I don't wish). Hence, I chose multiple nearby keywords to make the replacement.

**Comment by fschaeck** [comment]
If you put ('FY21/22','FY22/23') first, than any text in the slides that shows 'FY21/22' will be replaced with 'FY22/23'. Therefore if you have the term 'FY21/22 / FY22/23' anywhere, processing the first replacement will change that to 'FY22/23 / FY22/23' and thus the replacement at index 16 won‘t ever be able to match 'FY21/22 / FY22/23' since it has already been changed to 'FY22/23 / FY22/23'.

All you have to do is, to list the longer matches first! Move the replacement at index 16 all the way up to first position and the problem is gone. It will change the / to an or before the other replacement can get in the way.

For the second warning it is the same situation, but here the result for both replacements is actually the same, that is, why the replacement at index 19 is obsolete. It will never match but because the replacement at index 0 already produced the desired result anyway, it is just obsolete.

**Comment by SSMK-wq** [comment]
Great. But for 1st warning, even without putting longer string at the first, it managed to replace "/" with "or". I don't know how. That's why I was wondering why there is a warning (when replacement is successful). Anyway, i will put the longer string at first position going forward. Thanks
